#from https://github.com/CommitChange/globalid/blob/9d15bf2e931ac6ed4ba17936186657bd2001a2e4/.github/workflows/ci.yml
name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6' ]
        rails: [ '4.2']

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
        continue-on-error: ${{ matrix.ruby == 'head' || matrix.ruby == 'truffleruby' || matrix.rails == 'main' }}
        timeout-minutes: 3